package:
  name: qubekit
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

source:
  git_url: https://github.com/jthorton/QUBEKitdev.git

build:
  entry_points:
    - QUBEKit = QUBEKit.run:main
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  build:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6

about:
  home: https://github.com/jthorton/QUBEKitdev
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Quantum mechanical bespoke force field derivation toolkit
  doc_url: https://github.com/jthorton/QUBEKitdev

extra:
  recipe-maintainers:
    - CRingrose94