package:
  name: qubekit
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

source:
  git_url: https://github.com/jthorton/QUBEKitdev.git

build:
  entry_points:
    - QUBEKit = QUBEKit.run:main
  preserve_egg_dir: True
  script: python setup.py install

requirements:
  build:
    - setuptools
    - numpy
    - scipy
    - python >=3.6
    - matplotlib
    - networkx
    - rdkit::rdkit
    - omnia::openforcefield
    - openeye::openeye-toolkits
    - psi4::psi4
    - conda-forge::geomeTRIC
    - conda-forge::rdkit
  run:
    - numpy
    - scipy
    - python >=3.6
    - matplotlib
    - networkx
    - rdkit::rdkit
    - omnia::openforcefield
    - openeye::openeye-toolkits
    - psi4::psi4
    - conda-forge::geomeTRIC
    - conda-forge::rdkit

about:
  home: https://github.com/jthorton/QUBEKitdev
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Quantum mechanical bespoke force field derivation toolkit
  doc_url: https://github.com/jthorton/QUBEKitdev

extra:
  recipe-maintainers:
    - CRingrose94